name: CI -- linting, testing, building
run-name: ${{ github.actor }} is running CI actions

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on: 
    push:
        branches: [ master, dev ]
    pull_request:
        branches: [ master, dev ]
    workflow_dispatch:

jobs:
    pipeline:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        strategy:
            matrix:
                node-version: [ 17.4.0 ]
        # services:
        #   docker:
        #     image: docker:27-dind
        #     options: >-
        #       --privileged
        #       --entrypoint /usr/local/bin/dockerd-entrypoint.sh
        #       -e DOCKER_TLS_CERTDIR=/certs
        #       -e DOCKER_HOST=unix:///var/run/docker.sock
      
        steps:
          - uses: actions/checkout@v4
          - name: Installing Node.js ${{ matrix.node-version }} 
            uses: actions/setup-node@v4
            with:
                node-version: ${{ matrix.node-version }}    
          - name: Install modules
            run: npm install
          - name: Build project (production-build)
            run: npm run build:prod
            
          - name: Lint TS
            run: npm run lint:ts
            
          - name: Lint SCSS
            run: npm run lint:scss
            
          - name: Unit testing
            run: npm run test:unit
          
          # - name: Install Google Chrome
          #   run: |
          #     sudo apt-get update
          #     sudo apt-get install -y google-chrome-stable

          - name: Build storybook
            run: npm run storybook:build
            
          ##- name: Screenshot testing
          ##  run: npm run test:ui:ci
            